

version: 2
jobs:
  build:
    docker:
          - image:  cimg/node:16.20.0

    steps:
      - checkout
      - run: yarn install
      - run: CI=false yarn run build
      - run: yarn test:coverage
      - run: yarn run lint


  deploy_staging:
    parameters:
      env:
        type: string
        default: "staging"
    steps:
      - checkout
      - run: yarn install
      - run:
            name: creating staging build
            command: CI=false yarn run build:staging
      - run:
            name: firebase deploy

            command: ./node_modules/.bin/firebase deploy --token "$FIREBASE_TOKEN" --non-interactive --only hosting:<< parameters.env >>

  deploy_production:
    parameters:
      env:
        type: string
        default: "production"
    steps:
      - checkout
      - run: yarn install
      - run:
            name: creating production build
            command: CI=false yarn run build:production
      - run:
            name: firebase deploy
            command: ./node_modules/.bin/firebase deploy --token "$FIREBASE_TOKEN" --non-interactive --only hosting:<< parameters.env >>



workflows:
  version: 2

  staging:
    jobs:
      - deploy_staging:
          filters:
            branches:
              only: develop
  production:
    jobs:
      - deploy_production:
          filters:
            branches:
              only: main
