

version: 2
jobs:
  build:
    docker:
          - image:  cimg/node:16.20.0

    steps:
      - checkout
      - run: yarn install
      - run: CI=false yarn run build
      - run: yarn run lint
      - run: yarn test:coverage
