version: 2
jobs:
  build:
    docker:
      - image: cimg/node:16.20.0

    steps:
      - checkout
      - run: yarn install
      - run: CI=false yarn run build
      - run: yarn test:coverage
      - run: yarn run lint

  deploy_staging:
    parameters:
      env:
        type: string
        default: "staging"
    steps:
      - checkout
      - run: yarn install
      - run:
          name: creating staging build
          command: yarn run build
      - run:
          name: firebase deploy
          command: firebase use pipeline-dbe62
          command: ./node_modules/.bin/firebase deploy --token=$FIREBASE_DEPLOY_TOKEN


  # deploy_production:
  #   parameters:
  #     env:
  #       type: string
  #       default: "production"
  #   steps:
  #     - checkout
  #     - run: yarn install
  #     - run:
  #         name: creating production build
  #         command: yarn run build
  #     - run:
  #         name: firebase deploy
  #         command: ./node_modules/.bin/firebase deploy --token=$FIREBASE_DEPLOY_TOKEN




# workflows:
#   version: 2
#   deployment:
#     jobs:
#       - deploy_staging:
#           filters:
#             branches:
#               only: demo

#       - deploy_production:
#           filters:
#             branches:
#               only: main
